### ISSUE TITLE
[Bug]: Circuit kick message (TBS 1.10.0)

### ISSUE THREAD

**Issue by Shaolim132** [Writers-of-the-Script/Issue-Tracker#110]
### What happened?

SOMETIMES!!! When Circuit kicks you out of the game, it is just showing "Disconnected" Instead of "No more hiding/running" and 1 time I've got killed he didn't had kicked me out of the server for some reason.

### Version

1.10.0

### What operating system(s) do you experience this issue on?

Windows

### What Minecraft version were you on?

NeoForge 1.21.1

### Relevant log output

```shell

```

**Comment by PressureRach** [comment]
don't post an issue and instantly press complete, completing would mean the issue is fixed, reopen these if they aren't fixed.

**Comment by Shaolim132** [comment]
> don't post an issue and instantly press complete, completing would mean the issue is fixed, reopen these if they aren't fixed.

I don't think the bug is still happening thats why i closed (IDK HOW TO DELETE ISSUES PLEASE HELP)
